apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubelet-csr-approver.fullname" . }}
data:
  {{ .Values.configMap.data.scriptName }}: |
    {{- .Values.configMap.data.script | nindent 4 }}

