apiVersion: v1
kind: Pod
metadata:
  labels:
    run: csr-approver
  name: csr-approver
  namespace: kube-system
spec:
  containers:
    - image: cfmanteiga/alpine-bash-curl-jq
      name: csr-approver
      resources:
        requests:
          cpu: 1000m
          memory: 250Mi
        limits:
          cpu: 1000m
          memory: 250Mi
#      command:
#        - sleep
#      args:
#        - "86400"
      command: 
        - bash
      args:
        - -c
        - "while true; do sleep 10; bash /usr/local/bin/approve-csrs.sh; done"
      volumeMounts:
        - name: approve-csr-sh
          mountPath: /usr/local/bin
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  volumes:
    - name: approve-csr-sh
      configMap:
        name: approve-csr-sh  
  serviceAccountName: csr-approver